package com.xebia.entity;

import java.time.ZonedDateTime;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import io.swagger.annotations.ApiModelProperty;
import lombok.Data;


@JsonPropertyOrder({
    "slug_id",
    "slug",
    "title",
    "description",
    "body",
    "tags",
    "createdAt",
    "updatedAt",
    "favorited",
    "favoritesCount"
})
@Data
@Entity
public class Article {
	
	@Id
    @GeneratedValue(strategy = GenerationType.AUTO)	
	@JsonIgnore
	@ApiModelProperty(value = "autogenerated id")
	private Long id;
	
	@JsonProperty(value="id")
	@ApiModelProperty(value = "autogenerated UUid")
	private String slug_id;
	
	private String slug;
	
	private String title;
	
	private String description;

	private String body;

	private String[] tags;

	@ApiModelProperty(value = "Date of creation of resources")
	private ZonedDateTime createdAt;

	@ApiModelProperty(value = "Date of updation of resources")
	private ZonedDateTime updatedAt;

	private Boolean favorited;

	private Integer favoritesCount;


}
